spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://34.163.237.113:5432/plateform
        username: "postgres"
        password: "[CDGk@JZiN)'ZPsG"
#spring:
#    datasource:
#        driver-class-name: org.postgresql.Driver
#        url: jdbc:postgresql://localhost:5432/plateform
#        username: plateform
#        password: plateform
#        url: jdbc:postgresql://localhost:5432/game
#        username: plateforme
#        password: Isen14

    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB
